# Generated by Django 5.0 on 2024-01-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_profileinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
