# Generated by Django 5.0 on 2024-01-16 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_profileinfo_bio_profileinfo_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
